### ISSUE TITLE
setup test framework for portal integration tests

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/data-portal#237]
figure out what test framework to use for portal (webdriverio? Selenium? mabl?) and setup the configuration so that it can be run by jenkins

**Comment by trevars** [comment]
Issue with testing with Google.

**Comment by jbarno** [comment]
Since you guys are deploying much more frequently I think mabl would be a great fit for you. I've made a workspace:
https://app.mabl.com/workspaces/MQqK3ImQhO-7iF1IrKJHBw-w/settings/team

You can definitely trigger it to run on a number of different events. Let me know if you guys like it, I'm currently only using it to detect boken links with their crawlers.

**Comment by thanh-nguyen-dang** [comment]
https://github.com/uc-cdis/auto-qa/pull/1

**Comment by thanh-nguyen-dang** [comment]
spent 24 hours
